site_name: Technology Innovation Center - CoMakeIT
theme:
  name: material
  custom_dir: theme

  font:
    # text: Roboto Mono
    text: Roboto
  features:
    - navigation.tabs
    # - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow


    - header.autohide


  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: blue 
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name:  Switch to light mode    
      primary: dark blue
      accent: dark blue
nav:
  # - Home: index.md
  
  - Introduction:
    - Our Products: index.md
  - Developer's Guide:
    - DevelopersGuide/Concept.md
    - Mind Map:
      - Get Started : DevelopersGuide/MindMap/GetStarted.md
    - Generating-WDI:
      - Building WDI: DevelopersGuide/Generating-WDI/BuildingWDI.md
    - Generating-WDA (deprecated):
      - Building WDA: DevelopersGuide/Generating-WDA/BuildingWDA.md   
  - Documentation:
    - Architecture: Documentation/concept.md
    - Mind Map:
      - Introduction: Documentation/MindMap/Introduction.md
      - Pre-requisites: Documentation/MindMap/Prerequisites.md
      - UI+Gateway Node: Documentation/MindMap/UIandGateway.md
      - Service Node: Documentation/MindMap/ServiceNode.md
      - Global Configurations: Documentation/MindMap/GlobalConfigurations.md
      - Project Structure: Documentation/MindMap/Projectstructure.md
    - WDI:
      - WDI: Documentation/WDI/WDI.md
      - Pre-requisites: Documentation/WDI/Prerequisites.md
    - Local Setup: Documentation/Localsetup.md
    - WDA (deprecated):
      - WDA: Documentation/WDA/WDA.md
      - Pre-requisites: Documentation/WDA/Prerequisites.md
      - Application: Documentation/WDA/Application.md
      - Deployment : Documentation/WDA/Deployment.md
      - Communication : Documentation/WDA/Communication.md
repo_name: coMakeIT-TIC.github.io
repo_url: https://github.com/coMakeIT-TIC/coMakeIT-TIC.github.io
plugins:
  - search
  - mkdocs-video:
        is_video: True
        video_muted: True
        video_controls: True
        css_style:

markdown_extensions:
  - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/coMakeIT-TIC/coMakeIT-TIC.github.io"  target="_blank" rel="noopener">TIC@CoMakeIT</a>
